apiVersion: v1
kind: Service
metadata:
  name: test-service-nginx-welcome
spec:
  type: NodePort
  selector:
    app: nginx-welcome-test
  ports:
    - protocol: TCP
      port: 8030
      targetPort: 80
      nodePort: 30036
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-welcome-test
  labels:
    app: nginx-welcome-test
spec:
  containers:
  - name: nginx-container
    image: praqma/network-multitool
    ports:
      - containerPort: 80